import React,{useEffect,useState} from 'react';
import {View,Pressable,TextInput,ActivityIndicator} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {Shell,ThemeProvider,palettes,Txt,Row,Card,Section,Tag,Btn,Icon,IconBtn,Empty,Meter,FormSheet,Confirm} from './src/ui';
import {useStore,exportFile,importFile} from './src/storage';
import {empty,validate,demo,today,uid,days,colors,weekday,lessonsOn,clashes,taskStatus,gradeAverage,removeCourse,minutes} from './src/domain.mjs';
const tabs=[{id:'home',label:'Сегодня',icon:'sunny-outline'},{id:'schedule',label:'Расписание',icon:'calendar-outline'},{id:'tasks',label:'Задания',icon:'checkbox-outline'},{id:'grades',label:'Оценки',icon:'school-outline'},{id:'settings',label:'Ещё',icon:'ellipsis-horizontal'}];
const theme=palettes.campus;
export default function App(){return <SafeAreaProvider><ThemeProvider value={theme}><StatusBar style="dark"/><Campus/></ThemeProvider></SafeAreaProvider>}
function Campus(){
 const store=useStore<any>('CampusMate.v1',empty,validate),data=store.data;
 const [tab,setTab]=useState('home'),[day,setDay]=useState(weekday()),[filter,setFilter]=useState('active'),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<any>(null),[confirm,setConfirm]=useState<any>(null),[now,setNow]=useState(new Date());
 useEffect(()=>{const timer=setInterval(()=>setNow(new Date()),30000);return()=>clearInterval(timer)},[]);
 const notify=async(action:()=>Promise<any>,message='Готово')=>{try{await action();setNotice(message)}catch(e:any){setNotice(e.message??'Не удалось выполнить действие')}};
 const ask=(title:string,text:string,action:()=>Promise<any>)=>setConfirm({title,text,onConfirm:async()=>{await action();setConfirm(null);setForm(null)}});
 const courseName=(id:string)=>data.courses.find((c:any)=>c.id===id)?.name??'Предмет';
 const options=data.courses.map((c:any)=>({value:c.id,label:c.name}));
 const requireCourse=()=>{if(data.courses.length)return true;setNotice('Сначала добавь предмет — после этого можно создать занятие, задание или оценку.');setTab('settings');course();return false;};
 function deleteRecord(collection:string,id:string){ask('Удалить запись?','Эта запись исчезнет из твоего учебного плана.',()=>store.update((d:any)=>({...d,[collection]:d[collection].filter((r:any)=>r.id!==id)})))}
 async function saveRecord(collection:string,row:any,value:any){await store.update((d:any)=>({...d,[collection]:row?d[collection].map((r:any)=>r.id===row.id?value:r):[...d[collection],value]}));setNotice('Сохранено на устройстве');}
 function course(row?:any){setForm({title:row?'Редактировать предмет':'Новый предмет',fields:[{key:'name',label:'Название',placeholder:'Например, Базы данных'},{key:'teacher',label:'Преподаватель',placeholder:'Можно оставить пустым'},{key:'color',label:'Цвет в расписании',options:colors.map((value,i)=>({value,label:['Фиолетовый','Бирюзовый','Оранжевый','Розовый','Синий','Зелёный'][i]}))}],initial:{name:row?.name??'',teacher:row?.teacher??'',color:row?.color??colors[data.courses.length%colors.length]},onSubmit:async(v:any)=>saveRecord('courses',row,{id:row?.id??uid(),name:v.name.trim(),teacher:v.teacher.trim(),color:v.color}),onDelete:row?()=>ask('Удалить предмет?', 'Также будут удалены все его занятия, задания и оценки. Сначала экспортируй данные, если они нужны.',()=>store.update((d:any)=>removeCourse(d,row.id))):undefined});}
 function lesson(row?:any){
 if(!requireCourse())return;
 setForm({title:row?'Редактировать занятие':'Новое занятие',fields:[{key:'courseId',label:'Предмет',options},{key:'day',label:'День недели',options:days.map((label,i)=>({value:String(i+1),label}))},{key:'start',label:'Начало · ЧЧ:ММ',placeholder:'09:00'},{key:'end',label:'Окончание · ЧЧ:ММ',placeholder:'10:20'},{key:'room',label:'Аудитория или ссылка',placeholder:'C1.2.205'},{key:'kind',label:'Тип занятия',options:['Лекция','Практика','Лабораторная'].map(label=>({value:label,label}))}],initial:{courseId:row?.courseId??data.courses[0].id,day:String(row?.day??day),start:row?.start??'09:00',end:row?.end??'10:20',room:row?.room??'',kind:row?.kind??'Лекция'},onSubmit:async(v:any)=>{
 const value={id:row?.id??uid(),courseId:v.courseId,day:Number(v.day),start:v.start.trim(),end:v.end.trim(),room:v.room.trim(),kind:v.kind};
 if(clashes(data.lessons,value))throw new Error('В это время уже есть занятие. Выбери другое время или измени существующую пару.');
 await saveRecord('lessons',row,value);setDay(value.day);
 },onDelete:row?()=>deleteRecord('lessons',row.id):undefined});
 }
 function task(row?:any){if(!requireCourse())return;setForm({title:row?'Редактировать задание':'Новое задание',fields:[{key:'title',label:'Что нужно сделать?',placeholder:'Например, лабораторная работа № 3'},{key:'courseId',label:'Предмет',options},{key:'due',label:'Срок · ГГГГ-ММ-ДД',placeholder:'2026-09-30'},{key:'priority',label:'Приоритет',options:['Обычный','Высокий'].map(label=>({value:label,label}))},{key:'note',label:'Заметка',type:'multiline',placeholder:'Требования или ссылка на материалы'}],initial:{title:row?.title??'',courseId:row?.courseId??data.courses[0].id,due:row?.due??today(),priority:row?.priority??'Обычный',note:row?.note??''},onSubmit:async(v:any)=>saveRecord('tasks',row,{id:row?.id??uid(),title:v.title.trim(),courseId:v.courseId,due:v.due.trim(),priority:v.priority,note:v.note.trim(),done:row?.done??false}),onDelete:row?()=>deleteRecord('tasks',row.id):undefined});}
 function grade(row?:any){if(!requireCourse())return;setForm({title:row?'Редактировать оценку':'Новая оценка',fields:[{key:'courseId',label:'Предмет',options},{key:'title',label:'За какую работу?',placeholder:'Например, первый рубежный контроль'},{key:'score',label:'Получено баллов',type:'number'},{key:'max',label:'Максимум баллов',type:'number'},{key:'weight',label:'Вес работы · обычно 1',type:'number'}],initial:{courseId:row?.courseId??data.courses[0].id,title:row?.title??'',score:row?String(row.score):'',max:row?String(row.max):'100',weight:row?String(row.weight):'1'},onSubmit:async(v:any)=>{if(!v.score.trim()||!v.max.trim()||!v.weight.trim())throw new Error('Заполни баллы, максимум и вес.');await saveRecord('grades',row,{id:row?.id??uid(),courseId:v.courseId,title:v.title.trim(),score:Number(v.score.replace(',','.')),max:Number(v.max.replace(',','.')),weight:Number(v.weight.replace(',','.'))});},onDelete:row?()=>deleteRecord('grades',row.id):undefined});}
 const todayLessons=lessonsOn(data.lessons,weekday());
 const currentMinutes=now.getHours()*60+now.getMinutes();
 const nextLesson=todayLessons.find((l:any)=>minutes(l.end)>currentMinutes);
 const remaining=data.tasks.filter((t:any)=>!t.done);
 function lessonList(rows:any[]){return rows.length?rows.map((l:any)=>{const c=data.courses.find((c:any)=>c.id===l.courseId);return <Pressable key={l.id} accessibilityRole="button" accessibilityLabel={'Изменить занятие: '+c.name} onPress={()=>lesson(l)}><Row style={{alignItems:'stretch'}}><View style={{width:52,paddingTop:14,gap:5}}><Txt weight="700" size={14}>{l.start}</Txt><Txt color="#979CAB" size={12}>{l.end}</Txt></View><Card style={{flex:1,borderLeftWidth:4,borderLeftColor:c.color,padding:16,gap:9}}><Row style={{justifyContent:'space-between'}}><Tag text={l.kind}/><Icon name="chevron-forward" size={17}/></Row><Txt weight="700" size={17}>{c.name}</Txt><Row><Icon name="location-outline" size={15}/><Txt size={13} color="#838A9A" style={{flex:1}}>{l.room||'Аудитория не указана'}</Txt></Row>{c.teacher&&<Txt size={12} color="#949AA8">{c.teacher}</Txt>}</Card></Row></Pressable>}):<Empty title="Свободный день" text="Занятий нет. Отдохни или добавь пару в своё расписание." action={<Btn title="Добавить занятие" secondary onPress={()=>lesson()}/>}/>}
 function taskList(rows:any[]){return rows.length?rows.map((t:any)=>{const status=taskStatus(t);return <Card key={t.id} style={{padding:16}}><Row style={{alignItems:'flex-start'}}><Pressable accessibilityRole="checkbox" accessibilityLabel={'Выполнено: '+t.title} accessibilityState={{checked:t.done}} onPress={()=>notify(()=>store.update((d:any)=>({...d,tasks:d.tasks.map((item:any)=>item.id===t.id?{...item,done:!item.done}:item)})),'Статус задания обновлён')} style={{padding:7,minHeight:44,minWidth:40}}><Icon name={t.done?'checkbox':'square-outline'} color={t.done?theme.accent:'#ACB2C4'} size={25}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel={'Изменить задание: '+t.title} onPress={()=>task(t)} style={{flex:1,gap:7}}><Txt weight="600" style={{textDecorationLine:t.done?'line-through':'none'}}>{t.title}</Txt><Txt size={12} color="#838A9C">{courseName(t.courseId)}</Txt><Row style={{flexWrap:'wrap',gap:8}}><Tag text={status==='done'?'Готово':status==='overdue'?'Просрочено':status==='today'?'Сегодня':t.due.split('-').reverse().join('.')} color={status==='overdue'?'#FFE8E4':status==='done'?'#E6F3EB':undefined}/>{t.priority==='Высокий'&&!t.done&&<Txt size={12} color="#B67742">Высокий приоритет</Txt>}</Row></Pressable></Row></Card>}):<Empty title={filter==='done'?'Выполненных заданий пока нет':'Всё под контролем'} text="Добавляй дедлайны и отмечай сделанное." action={<Btn title="Новое задание" secondary onPress={()=>task()}/>}/>}
 async function restore(){const imported=await importFile();if(!imported)return;validate(imported);ask('Восстановить копию?',`Предметов: ${imported.courses.length}, заданий: ${imported.tasks.length}. Текущий учебный план будет заменён.`,()=>store.update(()=>imported));}
 async function shareSchedule(){const lines=['Моё расписание · CampusMate',''];for(let i=1;i<=7;i++){const list=lessonsOn(data.lessons,i);if(list.length){lines.push(days[i-1]);list.forEach((l:any)=>lines.push(`${l.start}–${l.end} · ${courseName(l.courseId)} · ${l.room||'без аудитории'}`));lines.push('')}}await exportFile('CampusMate-schedule.txt',lines.join('\n'),'text/plain');}
 return <><Shell name="CampusMate" subtitle="Учёба в твоём ритме" icon="school-outline" tab={tab} setTab={setTab} tabs={tabs} notice={notice||store.warning} busy={store.busy} demo={data.demo}>
 {!store.ready?(store.error?<Empty title="Не удалось прочитать данные" text={store.error} action={<View style={{gap:10}}><Btn title="Повторить" onPress={store.reload}/><Btn secondary title="Импортировать копию" onPress={()=>notify(restore,'Файл проверен')}/><Btn danger title="Начать заново" onPress={()=>ask('Начать с чистого листа?','Текущие данные будут заменены пустым учебным планом.',()=>store.update(()=>({...empty(),initialized:true})))}/></View>}/>:<ActivityIndicator size="large" color={theme.accent}/>):
 !data.initialized?<><Card style={{backgroundColor:theme.dark,padding:28,gap:20,borderWidth:0}}><Tag text="ТВОЙ ЛИЧНЫЙ УЧЕБНЫЙ ПЛАН" color="#DFFFAB"/><Icon name="planet-outline" color="#DFFFAB" size={60}/><Txt size={33} weight="800" color="#fff">Меньше хаоса.{"\n"}Больше ясности.</Txt><Txt color="#CECCE8">Пары, дедлайны и оценки — в одном месте. Освободи голову для того, что тебе интересно.</Txt></Card><Card><Txt size={20} weight="700">Настроим твою неделю?</Txt><Txt color="#7D8598">Добавь свои предметы и расписание. Подключения к университету нет: все записи заполняются вручную.</Txt><Btn title="Создать свой учебный план" onPress={()=>notify(()=>store.update(()=>({...empty(),initialized:true})),'Начни с добавления предметов в разделе «Ещё»')}/><Btn secondary title="Посмотреть демо" onPress={()=>notify(()=>store.update(demo),'Это пример, а не расписание AITU')}/></Card></>:
 <>
 {tab==='home'&&<>
 <Row style={{justifyContent:'space-between'}}><View><Txt size={13} color="#848A9B" style={{textTransform:'capitalize'}}>{now.toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'})}</Txt><Txt size={28} weight="800">Твой день</Txt></View><Tag text={todayLessons.length+' занятия'}/></Row>
 <Card style={{backgroundColor:theme.dark,padding:24,borderWidth:0,gap:16}}><Row style={{justifyContent:'space-between'}}><Txt color="#CEC9EB" size={13}>{nextLesson?(minutes(nextLesson.start)<=currentMinutes?'Сейчас идёт':'Следующая пара'):'На сегодня всё'}</Txt><Icon name="sparkles-outline" color="#DFFFAB"/></Row><Txt size={27} weight="700" color="#fff">{nextLesson?courseName(nextLesson.courseId):'Есть время для себя.'}</Txt><Txt color="#D8D5ED">{nextLesson?`${nextLesson.start}–${nextLesson.end}  ·  ${nextLesson.room||'Аудитория не указана'}`:'Посмотри задания или спланируй следующую неделю.'}</Txt><Row style={{paddingTop:15,borderTopWidth:1,borderColor:'#FFFFFF25'}}><View style={{flex:1}}><Txt size={25} weight="800" color="#DFFFAB">{remaining.length}</Txt><Txt size={12} color="#C9C5E3">заданий в работе</Txt></View><View style={{flex:1}}><Txt size={25} weight="800" color="#fff">{data.courses.length}</Txt><Txt size={12} color="#C9C5E3">предметов</Txt></View></Row></Card>
 <Section title="Расписание на сегодня" right={<Btn title="Неделя" small secondary onPress={()=>{setDay(weekday());setTab('schedule')}}/>}/>{lessonList(todayLessons)}
 <Section title="Ближайшие дедлайны" right={<IconBtn name="add" label="Добавить задание" onPress={()=>task()}/>}/>{taskList([...remaining].sort((a,b)=>a.due.localeCompare(b.due)).slice(0,3))}
 </>}
 {tab==='schedule'&&<><Section title="Твоя неделя" right={<Btn title="Занятие" small onPress={()=>lesson()}/>}/><Row style={{gap:6,justifyContent:'space-between'}}>{days.map((label,i)=><Pressable key={label} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{selected:day===i+1}} onPress={()=>setDay(i+1)} style={{flex:1,alignItems:'center',backgroundColor:day===i+1?theme.accent:'#fff',borderRadius:13,paddingVertical:16,borderWidth:1,borderColor:day===i+1?theme.accent:'#E5E7F0'}}><Txt size={13} weight="600" color={day===i+1?'#fff':'#8C91A3'}>{label}</Txt></Pressable>)}</Row><Txt size={13} color="#838B9A">Еженедельное расписание · нажми на пару для изменения</Txt>{lessonList(lessonsOn(data.lessons,day))}<Btn secondary title="Сохранить расписание для друзей" icon="share-outline" onPress={()=>notify(shareSchedule,'Подготовлен текстовый файл расписания')}/></>}
 {tab==='tasks'&&<><Section title="Задания" right={<Btn title="Добавить" small onPress={()=>task()}/>}/><Row>{[['active','В работе'],['done','Готово'],['all','Все']].map(([id,label])=><Btn key={id} small title={label} secondary={filter!==id} onPress={()=>setFilter(id)}/>)}</Row><TextInput accessibilityLabel="Поиск заданий" placeholder="Название задания или предмет" value={search} onChangeText={setSearch} style={{padding:15,borderWidth:1,borderColor:'#E0E3EC',backgroundColor:'#fff',borderRadius:14,fontSize:15}}/>{taskList([...data.tasks].filter((t:any)=>(filter==='all'||t.done===(filter==='done'))&&(t.title+' '+courseName(t.courseId)).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.due.localeCompare(b.due)))}</>}
 {tab==='grades'&&<><Section title="Твой прогресс" right={<Btn title="Оценка" small onPress={()=>grade()}/>}/><Card style={{backgroundColor:theme.soft,borderWidth:0}}><Txt size={13} color="#77749C">Средний результат по работам</Txt><Txt size={39} weight="800" color={theme.accent}>{gradeAverage(data.grades)===null?'—':gradeAverage(data.grades)!.toFixed(1)+'%'}</Txt><Txt size={12} color="#77749C">Средневзвешенный процент по введённым работам. Это не официальный GPA университета.</Txt></Card>
 {data.courses.length?data.courses.map((c:any)=>{const grades=data.grades.filter((g:any)=>g.courseId===c.id),avg=gradeAverage(grades);return <Card key={c.id}><Row style={{justifyContent:'space-between'}}><Txt weight="700" style={{flex:1}}>{c.name}</Txt><Txt weight="700" color={c.color}>{avg===null?'—':avg.toFixed(1)+'%'}</Txt></Row><Meter value={(avg??0)/100} color={c.color}/>{grades.length?grades.map((g:any)=><Pressable key={g.id} accessibilityRole="button" accessibilityLabel={'Изменить оценку: '+g.title} onPress={()=>grade(g)}><Row style={{paddingVertical:12,borderTopWidth:1,borderColor:'#EEF0F6'}}><View style={{flex:1}}><Txt size={14}>{g.title}</Txt><Txt size={12} color="#979CAE">Вес: {g.weight}</Txt></View><Txt weight="700" color={c.color}>{g.score} / {g.max}</Txt><Icon name="chevron-forward" size={16}/></Row></Pressable>):<Txt size={13} color="#8A92A1">Оценок пока нет</Txt>}</Card>}):<Empty title="Добавь первый предмет" text="Затем можно будет вести оценки и видеть прогресс." action={<Btn title="Добавить предмет" onPress={()=>course()}/>}/>}
 </>}
 {tab==='settings'&&<><Section title="Мои предметы" right={<Btn title="Добавить" small onPress={()=>course()}/>}/>{data.courses.map((c:any)=><Pressable key={c.id} accessibilityRole="button" accessibilityLabel={'Изменить предмет: '+c.name} onPress={()=>course(c)}><Card style={{padding:16}}><Row><View style={{height:38,width:6,borderRadius:5,backgroundColor:c.color}}/><View style={{flex:1}}><Txt weight="700">{c.name}</Txt><Txt size={12} color="#8B93A2">{c.teacher||'Преподаватель не указан'}</Txt></View><Icon name="chevron-forward" size={20}/></Row></Card></Pressable>)}
 {!data.courses.length&&<Empty title="Начни с предметов" text="Добавь названия курсов, которые изучаешь в этом семестре."/>}
 <Section title="Данные и перенос"/><Card><Txt color="#7C8596">Учебный план хранится на этом устройстве. Чтобы перенести его на другое или сохранить перед переустановкой, экспортируй JSON-копию.</Txt><Btn title="Экспортировать резервную копию" icon="download-outline" onPress={()=>notify(()=>exportFile('CampusMate-'+today()+'.json',JSON.stringify(data,null,2)),'Копия подготовлена')}/><Btn title="Импортировать копию" secondary onPress={()=>notify(restore,'Файл проверен')}/><Btn title="Поделиться только расписанием" secondary onPress={()=>notify(shareSchedule,'Подготовлен текстовый файл без оценок и заданий')}/></Card>
 <Card><Txt weight="700">Твой личный учебный помощник</Txt><Txt size={13} color="#838B9B">CampusMate не подключён к системам AITU. Расписание и оценки вводятся вручную. Синхронизации и фоновых уведомлений пока нет. Дедлайны отображаются при открытии приложения.</Txt></Card>
 <Btn danger title={data.demo?'Убрать демо и начать свой план':'Очистить учебный план'} onPress={()=>ask('Очистить учебный план?','Предметы, занятия, задания и оценки будут удалены с этого устройства. Сначала сохрани резервную копию.',()=>store.update(()=>({...empty(),initialized:true})))}/><Txt color="#8F95A3" size={12} style={{textAlign:'center'}}>CampusMate 1.0 · Больше времени на важное</Txt></>}
 </>}
 </Shell>{form&&<FormSheet {...form} onClose={()=>setForm(null)}/>} {confirm&&<Confirm {...confirm} onCancel={()=>setConfirm(null)}/>}</>;
}
