import {mkdir,writeFile} from 'node:fs/promises';
import {zstdDecompressSync} from 'node:zlib';
const release='2026-27';
const upstream=`https://github.com/manami-project/anime-offline-database/releases/download/${release}/anime-offline-database-minified.json.zst`;
const response=await fetch(upstream,{signal:AbortSignal.timeout(90000)});
if(!response.ok)throw Error('Dataset download: '+response.status);
const source=JSON.parse(zstdDecompressSync(Buffer.from(await response.arrayBuffer())).toString());
const genres=['action','adventure','comedy','drama','fantasy','romance','mystery','sci-fi','sports','slice of life','supernatural','thriller'];
const priority=[52991,5114,9253,11061,16498,38000,32281,21,1535,40028,1735,40748,1,20583,199,37521,48926,41467,40861];
const records=source.data.map(a=>{const mal=a.sources.find(s=>/^https:\/\/myanimelist.net\/anime\/\d+/.test(s));if(!mal)return null;return {id:Number(mal.match(/anime\/(\d+)/)[1]),title:a.title,aliases:a.synonyms,type:a.type,episodes:a.episodes,status:a.status,year:a.animeSeason?.year??null,score:Math.round((a.score?.arithmeticMean??0)*10)/10,image:a.picture,genres:a.tags.filter(t=>genres.includes(t)),tags:a.tags,studios:a.studios,source:mal};}).filter(Boolean);
const classic=records.find(a=>a.title==='Namakura Gatana');
if(!classic)throw Error('Classic title missing from upstream');
priority.push(classic.id);
console.log('Classic title ID:',classic.id);
const chosen=records.filter(a=>a.id===40861||priority.includes(a.id)||(['TV','MOVIE','ONA'].includes(a.type)&&['FINISHED','ONGOING'].includes(a.status)&&a.episodes>0&&a.score>=7&&a.year>=1990&&!a.tags.some(t=>/hentai|ecchi|explicit sex|pornograph/.test(t)))).sort((a,b)=>{const ai=priority.indexOf(a.id),bi=priority.indexOf(b.id);return (ai<0?999:ai)-(bi<0?999:bi)||b.score-a.score;}).slice(0,600).map(({tags,...a})=>a);
if(!chosen.some(a=>a.id===40861))throw Error('Required watchable series missing');
await mkdir('dist/data',{recursive:true});
await writeFile('dist/data/catalog.json',JSON.stringify({license:source.license,repository:source.repository,upstream,release,lastUpdate:source.lastUpdate,modifications:'Selection of 600 titles; simplified fields; scores rounded to one decimal. Original metadata by manami-project and its listed providers.',data:chosen},null,2));
const license=await fetch('https://raw.githubusercontent.com/manami-project/anime-offline-database/master/LICENSE');
if(!license.ok)throw Error('License download failed');
await writeFile('dist/data/LICENSE-ODbL.txt',await license.text());
console.log(JSON.stringify({count:chosen.length,updated:source.lastUpdate,pokemon:chosen.find(a=>a.id===40861),first:chosen.slice(0,4).map(({id,title,image})=>({id,title,image}))},null,2));
