<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><ApplicationIcon>Assets/Svetolesye.ico</ApplicationIcon><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable><AssemblyName>Svetolesye</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../Svetolesye.Core/Svetolesye.Core.csproj" /></ItemGroup><ItemGroup><Resource Include="Assets/Svetolesye.ico" /></ItemGroup><ItemGroup><Content Include="Assets/Audio/**/*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup></Project>
