import React,{createContext,useContext,useState,useEffect} from 'react';
import {View,Text,Pressable,TextInput,Modal,ScrollView,KeyboardAvoidingView,Platform,StyleSheet,ActivityIndicator,Alert} from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import {SafeAreaView} from 'react-native-safe-area-context';
export const palettes={campus:{accent:'#5550D9',soft:'#EEEDFF',dark:'#25244D',bg:'#F7F7FB'},budget:{accent:'#167363',soft:'#E7F3EC',dark:'#153F36',bg:'#F7F9F6'}};
const Theme=createContext(palettes.campus);
export const ThemeProvider=Theme.Provider;
export function Icon({name,size=22,color}:{name:any;size?:number;color?:string}){const t=useContext(Theme);return <Ionicons name={name} size={size} color={color??t.accent}/>;}
export function Txt({children,size=15,color='#252A39',weight='400',style}:any){return <Text style={[{fontSize:size,color,fontWeight:weight,lineHeight:size*1.42},style]}>{children}</Text>;}
export function Row({children,style}:any){return <View style={[{flexDirection:'row',alignItems:'center',gap:12},style]}>{children}</View>;}
export function Card({children,style}:any){return <View style={[{backgroundColor:'#fff',borderRadius:22,padding:20,borderWidth:1,borderColor:'#E8EAF0',gap:12},style]}>{children}</View>;}
export function Section({title,right}:any){return <Row style={{justifyContent:'space-between',marginTop:10,marginBottom:0}}><Txt size={20} weight="700" style={{flex:1}}>{title}</Txt>{right}</Row>;}
export function Tag({text,color}:any){const t=useContext(Theme);return <View style={{backgroundColor:color??t.soft,paddingHorizontal:10,paddingVertical:5,borderRadius:8,alignSelf:'flex-start'}}><Txt size={12} weight="600" color={t.dark}>{text}</Txt></View>;}
export function Btn({title,onPress,secondary=false,danger=false,icon,disabled=false,small=false}:any){const t=useContext(Theme);return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={({pressed})=>({backgroundColor:danger?'#FFF0F0':secondary?t.soft:t.accent,borderRadius:14,paddingVertical:small?10:15,paddingHorizontal:small?13:18,minHeight:44,opacity:disabled?.45:pressed?.72:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8})}>{icon&&<Icon name={icon} size={19} color={secondary?t.accent:'#fff'}/>}<Txt weight="700" size={small?13:15} color={danger?'#B63A45':secondary?t.accent:'#fff'}>{title}</Txt></Pressable>;}
export function IconBtn({name,label,onPress}:any){return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={{padding:10,minWidth:44,minHeight:44,alignItems:'center',justifyContent:'center'}}><Icon name={name}/></Pressable>;}
export function Empty({title,text,action}:any){return <Card style={{alignItems:'center',paddingVertical:30}}><Icon name="sparkles-outline" size={32}/><Txt size={18} weight="700">{title}</Txt><Txt color="#737A8A" style={{textAlign:'center'}}>{text}</Txt>{action}</Card>;}
export function Meter({value,color}:any){const t=useContext(Theme);return <View style={{height:8,backgroundColor:'#E8EDEB',borderRadius:8,overflow:'hidden'}}><View style={{height:8,width:`${Math.max(0,Math.min(100,value*100))}%`,backgroundColor:color??t.accent,borderRadius:8}}/></View>;}
export function Shell({name,subtitle,icon,tab,setTab,tabs,children,notice,busy,demo}:any){const t=useContext(Theme);return <SafeAreaView style={{flex:1,backgroundColor:t.bg}} edges={['top','bottom']}><View style={{flex:1,width:'100%',maxWidth:680,alignSelf:'center'}}><View style={{paddingHorizontal:22,paddingTop:16,paddingBottom:18}}><Row><View style={{backgroundColor:t.accent,width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center'}}><Icon name={icon} color="#fff" size={24}/></View><View style={{flex:1}}><Txt size={22} weight="800">{name}</Txt><Txt color="#838A98" size={12}>{subtitle}</Txt></View><View style={{width:39,height:39,borderRadius:20,backgroundColor:t.soft,alignItems:'center',justifyContent:'center'}}><Icon name="person-outline" size={19}/></View></Row></View>
{demo&&<View style={{backgroundColor:'#FFF3D8',paddingHorizontal:22,paddingVertical:9}}><Txt size={12} color="#805B20">Демо-данные · свои записи начни в настройках</Txt></View>}
{notice&&<View accessibilityLiveRegion="polite" style={{paddingHorizontal:22,paddingVertical:10,backgroundColor:t.soft}}><Txt size={13}>{notice}</Txt></View>}
<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,paddingTop:12,gap:18,paddingBottom:35}}>{children}</ScrollView>
<View style={{flexDirection:'row',backgroundColor:'#fff',borderTopWidth:1,borderColor:'#E8EAF0',paddingTop:10,paddingBottom:7}}>{tabs.map((item:any)=><Pressable key={item.id} accessibilityRole="tab" accessibilityState={{selected:tab===item.id}} accessibilityLabel={item.label} onPress={()=>setTab(item.id)} style={{flex:1,alignItems:'center',gap:4,paddingVertical:6,minHeight:50}}><Icon name={item.icon} size={22} color={tab===item.id?t.accent:'#9399A6'}/><Txt size={11} weight={tab===item.id?'700':'400'} color={tab===item.id?t.accent:'#858C9A'}>{item.label}</Txt></Pressable>)}</View>{busy&&<View pointerEvents="none" style={{position:'absolute',top:7,right:8}}><ActivityIndicator color={t.accent}/></View>}</View></SafeAreaView>;}
export type Field={key:string;label:string;placeholder?:string;type?:'number'|'multiline';options?:{value:string;label:string}[]};
export function FormSheet({title,fields,initial,onSubmit,onClose,onDelete}: {title:string;fields:Field[];initial:any;onSubmit:(v:any)=>Promise<void>|void;onClose:()=>void;onDelete?:()=>void}){
const [values,setValues]=useState<any>(initial),[error,setError]=useState(''),[saving,setSaving]=useState(false);const t=useContext(Theme);
return <Modal animationType="slide" transparent visible onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={{flex:1,backgroundColor:'#151D3966',justifyContent:'flex-end'}}><SafeAreaView edges={['bottom','top']} style={{backgroundColor:'#fff',borderTopLeftRadius:28,borderTopRightRadius:28,maxHeight:'94%',width:'100%',maxWidth:680,alignSelf:'center'}}><Row style={{padding:20,borderBottomWidth:1,borderColor:'#EEEFF4'}}><Txt size={22} weight="700" style={{flex:1}}>{title}</Txt><IconBtn name="close" label="Закрыть форму" onPress={()=>!saving&&onClose()}/></Row><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:22,gap:20}}>{fields.map(field=><View key={field.key} style={{gap:9}}><Txt size={14} weight="600">{field.label}</Txt>{field.options?<View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{field.options.map(option=><Pressable key={option.value} accessibilityRole="radio" accessibilityState={{checked:String(values[field.key])===option.value}} onPress={()=>setValues({...values,[field.key]:option.value})} style={{paddingHorizontal:13,paddingVertical:11,borderRadius:11,backgroundColor:String(values[field.key])===option.value?t.accent:t.soft}}><Txt size={13} color={String(values[field.key])===option.value?'#fff':t.dark}>{option.label}</Txt></Pressable>)}</View>:<TextInput accessibilityLabel={field.label} value={String(values[field.key]??'')} onChangeText={value=>setValues({...values,[field.key]:value})} placeholder={field.placeholder} placeholderTextColor="#959CAA" keyboardType={field.type==='number'?'decimal-pad':'default'} multiline={field.type==='multiline'} maxLength={field.type==='multiline'?500:100} style={{borderWidth:1,borderColor:'#DEE2EC',borderRadius:13,padding:14,fontSize:16,color:'#252A39',backgroundColor:'#FAFBFE',minHeight:field.type==='multiline'?90:51,textAlignVertical:'top'}}/>}</View>)}{error&&<Txt color="#B63A45" style={{backgroundColor:'#FFF0F0',padding:12,borderRadius:10}}>{error}</Txt>}<Btn title={saving?'Сохраняем…':'Сохранить'} disabled={saving} onPress={async()=>{setSaving(true);setError('');try{await onSubmit(values);onClose();}catch(e:any){setError(e.message??'Не удалось сохранить');}finally{setSaving(false)}}}/>{onDelete&&<Btn danger title="Удалить запись" disabled={saving} onPress={onDelete}/>}</ScrollView></SafeAreaView></KeyboardAvoidingView></Modal>;
}
function NativeConfirm({title,text,onCancel,onConfirm}:any){useEffect(()=>{Alert.alert(title,text,[{text:'Отмена',style:'cancel',onPress:onCancel},{text:'Подтвердить',style:'destructive',onPress:()=>{Promise.resolve(onConfirm()).catch((e:any)=>{Alert.alert('Не удалось выполнить действие',e.message);onCancel();});}}],{cancelable:true,onDismiss:onCancel});},[]);return null;}
export function Confirm(props:any){return Platform.OS==='web'?<WebConfirm {...props}/>:<NativeConfirm {...props}/>}
function WebConfirm({title,text,onCancel,onConfirm}:any){const[error,setError]=useState(''),[busy,setBusy]=useState(false);return <Modal transparent visible animationType="fade" onRequestClose={onCancel}><View style={{flex:1,backgroundColor:'#151D3977',justifyContent:'center',padding:26}}><Card style={{width:'100%',maxWidth:480,alignSelf:'center',gap:18}}><Txt size={22} weight="700">{title}</Txt><Txt color="#6E7789">{text}</Txt>{error&&<Txt color="#B63A45">{error}</Txt>}<Btn title={busy?'Подожди…':'Подтвердить'} disabled={busy} onPress={async()=>{setBusy(true);try{await onConfirm();}catch(e:any){setError(e.message)}finally{setBusy(false)}}}/><Btn title="Отмена" secondary disabled={busy} onPress={onCancel}/></Card></View></Modal>;}
