import React,{useState} from 'react';
import {View,Pressable,TextInput,ActivityIndicator} from 'react-native';
import {StatusBar} from 'expo-status-bar';
import {SafeAreaProvider} from 'react-native-safe-area-context';
import {Shell,ThemeProvider,palettes,Txt,Row,Card,Section,Tag,Btn,Icon,IconBtn,Empty,Meter,FormSheet,Confirm,Field} from './src/ui';
import {useStore,exportFile,importFile} from './src/storage';
import {empty,validate,demo,today,uid,parseMoney,money,summary,monthName,monthShift,categories,incomeCategories,csv} from './src/domain.mjs';
const tabs=[{id:'home',label:'Обзор',icon:'grid-outline'},{id:'history',label:'Операции',icon:'swap-horizontal-outline'},{id:'budget',label:'Планы',icon:'pie-chart-outline'},{id:'settings',label:'Настройки',icon:'settings-outline'}];
const theme=palettes.budget;
export default function App(){return <SafeAreaProvider><ThemeProvider value={theme}><StatusBar style="dark"/><Budget/></ThemeProvider></SafeAreaProvider>}
function Budget(){
 const store=useStore<any>('PocketBudget.v1',empty,validate),data=store.data;
 const [tab,setTab]=useState('home'),[month,setMonth]=useState(today().slice(0,7)),[filter,setFilter]=useState('all'),[search,setSearch]=useState(''),[notice,setNotice]=useState(''),[form,setForm]=useState<any>(null),[confirm,setConfirm]=useState<any>(null);
 const totals=summary(data.transactions,month);
 const notify=async(action:()=>Promise<any>,message='Готово')=>{try{await action();setNotice(message)}catch(e:any){setNotice(e.message??'Не удалось выполнить действие')}};
 const ask=(title:string,text:string,action:()=>Promise<any>)=>setConfirm({title,text,onConfirm:async()=>{await action();setConfirm(null);setForm(null)}});
 function deleteRecord(collection:string,id:string){ask('Удалить запись?','Удаление изменит расчёты. Предыдущая версия останется в автоматической резервной копии.',()=>store.update((d:any)=>({...d,[collection]:d[collection].filter((r:any)=>r.id!==id)})))}
 function transaction(type='expense',row?:any){
 const cat=type==='income'?incomeCategories:categories;
 setForm({title:row?'Редактировать операцию':type==='income'?'Новый доход':'Новый расход',fields:[{key:'amount',label:'Сумма, ₸',type:'number',placeholder:'Например, 2500'},{key:'category',label:'Категория',options:cat.map(c=>({value:c.id,label:c.name}))},{key:'date',label:'Дата · ГГГГ-ММ-ДД',placeholder:'2026-09-27'},{key:'note',label:'Комментарий',placeholder:'На что потратил или откуда получил',type:'multiline'}],
 initial:{amount:row?String(row.amount/100):'',category:row?.category??cat[0].id,date:row?.date??today(),note:row?.note??''},onSubmit:async(v:any)=>{
 const value={id:row?.id??uid(),type,amount:parseMoney(v.amount),category:v.category,date:v.date.trim(),note:v.note.trim()};
 await store.update((d:any)=>({...d,transactions:row?d.transactions.map((r:any)=>r.id===row.id?value:r):[value,...d.transactions]}));setMonth(value.date.slice(0,7));setNotice('Операция сохранена');
 },onDelete:row?()=>deleteRecord('transactions',row.id):undefined});
 }
 function budget(row?:any){setForm({title:row?'Изменить лимит':'Лимит на месяц',fields:[{key:'category',label:'Категория',options:categories.map(c=>({value:c.id,label:c.name}))},{key:'limit',label:'Лимит, ₸',type:'number',placeholder:'30000'}],initial:{category:row?.category??'food',limit:row?String(row.limit/100):''},onSubmit:async(v:any)=>{const value={id:row?.id??uid(),month,category:v.category,limit:parseMoney(v.limit)};await store.update((d:any)=>({...d,budgets:[...d.budgets.filter((b:any)=>b.id!==row?.id&&!(b.month===month&&b.category===v.category)),value]}));},onDelete:row?()=>deleteRecord('budgets',row.id):undefined});}
 function goal(row?:any){setForm({title:row?'Изменить цель':'Новая цель',fields:[{key:'name',label:'На что копишь?',placeholder:'Например, ноутбук'},{key:'target',label:'Нужно накопить, ₸',type:'number'},{key:'saved',label:'Уже отложено, ₸',type:'number'}],initial:{name:row?.name??'',target:row?String(row.target/100):'',saved:row?String(row.saved/100):'0'},onSubmit:async(v:any)=>{const saved=String(v.saved).trim();const value={id:row?.id??uid(),name:v.name.trim(),target:parseMoney(v.target),saved:/^0([.,]0{1,2})?$/.test(saved)?0:parseMoney(saved)};await store.update((d:any)=>({...d,goals:row?d.goals.map((g:any)=>g.id===row.id?value:g):[...d.goals,value]}));},onDelete:row?()=>deleteRecord('goals',row.id):undefined});}
 const monthPicker=<Row style={{justifyContent:'space-between'}}><IconBtn name="chevron-back" label="Предыдущий месяц" onPress={()=>setMonth(monthShift(month,-1))}/><Txt size={16} weight="600" style={{textTransform:'capitalize'}}>{monthName(month)}</Txt><IconBtn name="chevron-forward" label="Следующий месяц" onPress={()=>setMonth(monthShift(month,1))}/></Row>;
 const transactionList=(rows:any[])=>rows.length?rows.map(t=>{const c=[...categories,...incomeCategories].find(c=>c.id===t.category)!;return <Pressable key={t.id} accessibilityRole="button" accessibilityLabel={'Изменить: '+(t.note||c.name)} onPress={()=>transaction(t.type,t)}><Row style={{paddingVertical:14,borderBottomWidth:1,borderColor:'#EFF1F4'}}><View style={{padding:11,borderRadius:14,backgroundColor:t.type==='income'?'#E8F4EC':'#F3F3F8'}}><Icon name={t.type==='income'?'arrow-down-outline':(c as any).icon}/></View><View style={{flex:1}}><Txt weight="600">{t.note||c.name}</Txt><Txt size={12} color="#858D9A">{c.name} · {t.date.split('-').reverse().join('.')}</Txt></View><Txt weight="700" color={t.type==='income'?theme.accent:'#283D36'}>{t.type==='income'?'+':'−'}{money(t.amount)}</Txt></Row></Pressable>}):<Empty title="Здесь пока пусто" text="Добавь первую операцию за выбранный месяц." action={<Btn title="Добавить расход" onPress={()=>transaction()}/>}/>;
 async function restore(){const imported=await importFile();if(!imported)return;validate(imported);ask('Восстановить копию?',`Будет загружено операций: ${imported.transactions.length}. Текущие записи будут заменены; сначала можно экспортировать их.`,()=>store.update(()=>imported));}
 return <><Shell name="PocketBudget" subtitle="Деньги под твоим контролем" icon="wallet-outline" tab={tab} setTab={setTab} tabs={tabs} notice={notice||store.warning} busy={store.busy} demo={data.demo}>
 {!store.ready?(store.error?<Empty title="Не удалось прочитать данные" text={store.error} action={<View style={{gap:10}}><Btn title="Повторить" onPress={store.reload}/><Btn secondary title="Импортировать копию" onPress={()=>notify(restore,'Копия прочитана')}/><Btn danger title="Начать с пустых данных" onPress={()=>ask('Начать заново?','Текущие данные на этом устройстве будут заменены пустым списком.',()=>store.update(()=>({...empty(),initialized:true})))}/></View>}/>:<ActivityIndicator size="large" color={theme.accent}/>):
 !data.initialized?<><Card style={{backgroundColor:theme.dark,padding:28,gap:20}}><Tag text="ТВОИ ДЕНЬГИ · ТВОЙ РИТМ" color="#B9E7BA"/><Icon name="leaf-outline" color="#B9E7BA" size={55}/><Txt size={32} color="#fff" weight="800">Маленькие привычки.{"\n"}Большие планы.</Txt><Txt color="#BDD6CC">Записывай доходы и расходы, планируй месяц и двигайся к своим целям.</Txt></Card><Card><Txt size={20} weight="700">Начнём с чистого листа?</Txt><Txt color="#7C8590">Все суммы — в тенге. Данные хранятся на этом устройстве и не отправляются на сервер.</Txt><Btn title="Начать свой бюджет" onPress={()=>notify(()=>store.update(()=>({...empty(),initialized:true})),'Можно добавить первый доход')}/><Btn title="Посмотреть демо" secondary onPress={()=>notify(()=>store.update(demo),'Открыты демонстрационные данные')}/></Card></>:
 <>
 {(tab==='home'||tab==='history'||tab==='budget')&&monthPicker}
 {tab==='home'&&<>
 <Card style={{backgroundColor:theme.dark,padding:25,borderWidth:0,gap:18}}><Row style={{justifyContent:'space-between'}}><Txt color="#B7D8CB" size={14}>Итог месяца</Txt><Icon name="trending-up-outline" color="#B9E7BA"/></Row><Txt size={39} color="#fff" weight="800">{money(totals.net)}</Txt><Row style={{borderTopWidth:1,borderColor:'#FFFFFF25',paddingTop:18}}><View style={{flex:1,gap:5}}><Txt color="#AED0BD" size={12}>↓ Доходы</Txt><Txt color="#fff" size={19} weight="700">{money(totals.income)}</Txt></View><View style={{flex:1,gap:5}}><Txt color="#AED0BD" size={12}>↑ Расходы</Txt><Txt color="#fff" size={19} weight="700">{money(totals.expense)}</Txt></View></Row></Card>
 <Row><View style={{flex:1}}><Btn title="Расход" icon="add" onPress={()=>transaction()}/></View><View style={{flex:1}}><Btn title="Доход" secondary icon="arrow-down" onPress={()=>transaction('income')}/></View></Row>
 <Section title="Куда уходят деньги"/><Card>{categories.filter(c=>(totals.byCategory as any)[c.id]).length?categories.filter(c=>(totals.byCategory as any)[c.id]).sort((a,b)=>(totals.byCategory as any)[b.id]-(totals.byCategory as any)[a.id]).map(c=><View key={c.id} style={{gap:9,marginBottom:6}}><Row style={{justifyContent:'space-between'}}><Txt size={14}>{c.name}</Txt><Txt size={14} weight="600">{money((totals.byCategory as any)[c.id])}</Txt></Row><Meter value={(totals.byCategory as any)[c.id]/totals.expense} color={c.color}/></View>):<Txt color="#818B94">Категории появятся после первого расхода.</Txt>}</Card>
 <Section title="Последние операции" right={<Btn title="Все" small secondary onPress={()=>setTab('history')}/>}/><View>{transactionList([...totals.rows].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4))}</View>
 </>}
 {tab==='history'&&<><Section title="История" right={<Btn title="Добавить" small onPress={()=>transaction()}/>}/><Row>{[['all','Все'],['expense','Расходы'],['income','Доходы']].map(([id,label])=><Btn key={id} small title={label} secondary={filter!==id} onPress={()=>setFilter(id)}/>)}</Row><TextInput accessibilityLabel="Поиск операций" placeholder="Поиск по комментарию и категории" value={search} onChangeText={setSearch} style={{backgroundColor:'#fff',borderWidth:1,borderColor:'#DFE6E2',padding:15,borderRadius:14,fontSize:15}}/>{transactionList([...totals.rows].filter(t=>(filter==='all'||t.type===filter)&&(t.note+' '+[...categories,...incomeCategories].find(c=>c.id===t.category)?.name).toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date)))}<Btn secondary title="Добавить доход" onPress={()=>transaction('income')}/></>}
 {tab==='budget'&&<><Section title="Лимиты расходов" right={<Btn title="Добавить" small onPress={()=>budget()}/>}/><Txt color="#808996" size={13}>Лимиты действуют только на выбранный месяц. Нажми на карточку, чтобы изменить.</Txt>{data.budgets.filter((b:any)=>b.month===month).length?data.budgets.filter((b:any)=>b.month===month).map((b:any)=>{const spent=(totals.byCategory as any)[b.category]??0;return <Pressable key={b.id} accessibilityRole="button" accessibilityLabel={'Изменить лимит: '+categories.find(c=>c.id===b.category)!.name} onPress={()=>budget(b)}><Card><Row style={{justifyContent:'space-between'}}><Txt weight="700">{categories.find(c=>c.id===b.category)!.name}</Txt><Txt size={13} color={spent>b.limit?'#B63A45':theme.accent}>{Math.round(spent/b.limit*100)}%</Txt></Row><Meter value={spent/b.limit} color={spent>b.limit?'#D47777':theme.accent}/><Txt size={13} color="#7A8591">{money(spent)} из {money(b.limit)}</Txt><Txt size={13} color={spent>b.limit?'#B63A45':theme.accent}>{spent>b.limit?'Превышение: '+money(spent-b.limit):'Осталось: '+money(b.limit-spent)}</Txt></Card></Pressable>}):<Empty title="План на месяц" text="Задай комфортный лимит для одной или нескольких категорий."/>}
 <Section title="На что копим?" right={<Btn title="Цель" small secondary onPress={()=>goal()}/>}/><Txt size={13} color="#818B96">Накопления отмечаются вручную и не меняют историю операций.</Txt>{data.goals.length?data.goals.map((g:any)=><Pressable key={g.id} accessibilityRole="button" accessibilityLabel={'Изменить цель: '+g.name} onPress={()=>goal(g)}><Card><Row><Icon name="flag-outline"/><Txt size={18} weight="700" style={{flex:1}}>{g.name}</Txt><Txt weight="700">{Math.round(g.saved/g.target*100)}%</Txt></Row><Meter value={g.saved/g.target}/><Txt size={13} color="#7A8591">{money(g.saved)} из {money(g.target)}</Txt></Card></Pressable>):<Empty title="Первая цель" text="Поездка, ноутбук или подушка безопасности — выбери что-то своё."/>}</>}
 {tab==='settings'&&<><Section title="Твоё пространство"/><Card><Row><Icon name="phone-portrait-outline"/><View style={{flex:1}}><Txt weight="700">На этом устройстве</Txt><Txt size={13} color="#7D8591">Валюта: KZT · операций: {data.transactions.length}</Txt></View></Row><Txt color="#7D8591">Это личный журнал. Данные друзей будут храниться отдельно на их устройствах. Синхронизации между устройствами пока нет.</Txt></Card>
 <Section title="Резервная копия"/><Card><Txt color="#7D8591">Сохрани JSON-файл, чтобы перенести данные или восстановить их после переустановки. Файл содержит твои записи.</Txt><Btn title="Экспортировать копию" icon="download-outline" onPress={()=>notify(()=>exportFile('PocketBudget-'+today()+'.json',JSON.stringify(data,null,2)),'Копия подготовлена')}/><Btn title="Импортировать копию" secondary onPress={()=>notify(restore,'Файл проверен')}/><Btn title="Выгрузить все операции в CSV" secondary onPress={()=>notify(()=>exportFile('PocketBudget-operations.csv',csv(data.transactions),'text/csv;charset=utf-8'),'CSV подготовлен')}/></Card>
 <Card><Txt weight="700">Обновление и резервное копирование</Txt><Txt color="#7D8591" size={13}>При каждой записи сохраняется предыдущая корректная версия. Храни экспорт отдельно: браузер может очистить локальное хранилище, а удаление приложения — его данные.</Txt></Card><Btn danger title={data.demo?'Очистить демо и начать свой бюджет':'Очистить все записи'} onPress={()=>ask('Начать заново?','Все операции, лимиты и цели на этом устройстве будут очищены. Сначала экспортируй нужные данные.',()=>store.update(()=>({...empty(),initialized:true})))}/><Txt size={12} color="#8B939D" style={{textAlign:'center'}}>PocketBudget 1.0 · Сделано для твоих планов</Txt></>}
 </>}
 </Shell>{form&&<FormSheet key={form.title+(form.initial?.date??'')} {...form} onClose={()=>setForm(null)}/>} {confirm&&<Confirm {...confirm} onCancel={()=>setConfirm(null)}/>}</>;
}
